name: Pipeline prix bourse

on:
  schedule:
    # Tous les jours de semaine à 08:00 UTC
    # ≈ 09:00/10:00 en Europe/Paris selon l’heure d’été
    - cron: "5 22 * * *"
  workflow_dispatch: {}

jobs:
  run-pipeline:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          pip install yfinance tiingo pandas numpy

      - name: Run pipeline script
        env:
          TIINGO_API_KEY: ${{ secrets.TIINGO_API_KEY }}
        run: |
          python donne_collectes_nettoye.py

      - name: Commit and push changes
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "kizsnana@gmail.com"

          if [ -n "$(git status --porcelain)" ]; then
            git add data
            git commit -m "Auto: update prix $(date -u +"%Y-%m-%d %H:%M:%S")"
            git push
          else
            echo "Aucun changement à committer."
          fi
